import type { Metadata } from "next";
import { geistSans, geistMono, merienda } from "./fonts";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${merienda.variable} antialiased`}
      >
        {children}
      <Toaster/>
      </body>
    </html>
  );
}
